export const Actions = {
  SET_SESSION: 'SET_SESSION',
  GET_SESSION: 'GET_SESSION',
  UPDATE_SESSION: 'UPDATE_SESSION',
  GET_USERS_BY_DID: 'USERS/GET_USERS_BY_DID',
  GET_USERS_BY_DID_SUCCESS: 'USERS/GET_USERS_BY_DID_SUCCESS',
  GET_USERS_BY_DID_FAILURE: 'USERS/GET_USERS_BY_DID_FAILURE'
};
