version: '3.3'

services:
  hive-node:
    container_name: hive-node
    image: tuumtech/hive-node:v2.5.1
    user: '${UID}:${GID}'
    entrypoint: /bin/sh -c "python manage.py -c dev runserver"
    volumes:
      - ${HOME}/.profile-data/hive-data:/src/data
      - ${PWD}/docker/hive.env:/src/.env
    ports:
      - 9001:5000
    depends_on:
      - restapi-mongo
    networks:
      - profile
    tty: true

  assist-restapi-node:
    container_name: assist-restapi-node
    image: tuumtech/assist-restapi-node:latest
    user: '${UID}:${GID}'
    volumes:
      - ${PWD}/docker/assist-restapi.env:/src/.env
    ports:
      - 9002:5000
    depends_on:
      - restapi-mongo
    networks:
      - profile
    tty: true

  restapi-mongo:
    container_name: restapi-mongo
    image: mongo
    user: '${UID}:${GID}'
    volumes:
      - ${HOME}/.profile-data/restapi-mongo-data:/data/db
    ports:
      - 37018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    networks:
      - profile
    tty: true

  matrix-synapse-node:
    container_name: matrix-synapse-node
    image: matrixdotorg/synapse:latest
    user: '991:991'
    volumes:
      - ${HOME}/.profile-data/matrix-synapse-data:/data
      - ${PWD}/docker/matrix-synapse/homeserver.yaml:/data/homeserver.yaml
      - ${PWD}/docker/matrix-synapse/my.matrix.host.log.config:/data/my.matrix.host.log.config
      - ${PWD}/docker/matrix-synapse/my.matrix.host.signing.key:/data/my.matrix.host.signing.key
    ports:
      - 8008:8008
      - 8448:8448/tcp
    depends_on:
      - synapse-postgres
    networks:
      - profile
    tty: true

  synapse-postgres:
    container_name: synapse-postgres
    image: docker.io/postgres:12-alpine
    user: '${UID}:${GID}'
    volumes:
      - ${HOME}/.profile-data/synapse-postgres-data:/var/lib/postgresql/data
    ports:
      - 35432:5432
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    networks:
      - profile
    tty: true

networks:
  profile:
