version: "3.3"

services:
  hive-node:
    container_name: hive-node
    image: tuumtech/hive-node:latest
    user: "${UID}:${GID}"
    entrypoint: /bin/sh -c "python manage.py -c dev runserver"
    volumes:
      - ${HOME}/.profile-data/hive-data:/src/data
      - ${PWD}/docker/hive.env:/src/.env
    ports:
      - 9001:5000
    depends_on:
      - hive-mongo
    networks:
      - profile
    tty: true

  assist-restapi-node:
    container_name: assist-restapi-node
    image: tuumtech/assist-restapi-node:latest
    user: "${UID}:${GID}"
    volumes:
      - ${PWD}/docker/assist-restapi.env:/src/.env
    ports:
      - 9002:5000
    depends_on:
      - restapi-mongo
    networks:
      - profile
    tty: true

  vouch-restapi-node:
    container_name: vouch-restapi-node
    image: tuumtech/vouch-restapi-node:latest
    user: "${UID}:${GID}"
    volumes:
      - ${PWD}/docker/vouch-restapi.env:/src/.env
    ports:
      - 9003:5000
    depends_on:
      - restapi-mongo
      - restapi-redis
    networks:
      - profile
    tty: true

  didcreds-validator-node:
    container_name: didcreds-validator-node
    image: tuumtech/didcreds-validator-node:latest
    user: "${UID}:${GID}"
    volumes:
      - ${HOME}/.profile-data/didcreds-didstore:/src/data
      - ${PWD}/docker/didcreds-validator.env:/src/.env
    ports:
      - 9004:5000
    depends_on:
      - restapi-mongo
      - restapi-redis
      - vouch-restapi-node
    networks:
      - profile
    tty: true

  hive-mongo:
    container_name: hive-mongo
    image: mongo
    user: "${UID}:${GID}"
    volumes:
      - ${HOME}/.profile-data/hive-mongo-data:/data/db
    ports:
      - 37017:27017
    networks:
      - profile
    tty: true

  restapi-mongo:
    container_name: restapi-mongo
    image: mongo
    user: "${UID}:${GID}"
    volumes:
      - ${HOME}/.profile-data/restapi-mongo-data:/data/db
    ports:
      - 37018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    networks:
      - profile
    tty: true

  restapi-redis:
    container_name: restapi-redis
    image: redis
    user: "${UID}:${GID}"
    volumes:
      - ${HOME}/.profile-data/restapi-redis-data:/data
    ports:
      - 7379:6379
    networks:
      - profile
    tty: true

networks:
  profile:
