export const NameSpace = 'space';

export const Actions = {
  FETCH_SPACES: 'SPACES/FETCH_SPACES',
  FETCH_SPACES_SUCCESS: 'SPACES/FETCH_SPACES_SUCCESS',
  FETCH_SPACES_FAILURE: 'SPACES/FETCH_SPACES_FAILURE'
};
