export const NameSpace = 'space';

export const Actions = {
  FETCH_SPACES: 'SPACES/FETCH_SPACES',
  FETCH_SPACES_SUCCESS: 'SPACES/FETCH_SPACES_SUCCESS',
  FETCH_SPACES_FAILURE: 'SPACES/FETCH_SPACES_FAILURE',
  UPDATE_SPACE: 'SPACES/UPDATE_SPACE',
  UPDATE_SPACE_SUCCESS: 'SPACES/UPDATE_SPACE_SUCCESS',
  UPDATE_SPACE_FAILURE: 'SPACES/UPDATE_SPACE_FAILURE',
  REMOVE_SPACE: 'SPACES/REMOVE_SPACE',
  REMOVE_SPACE_SUCCESS: 'SPACES/REMOVE_SPACE_SUCCESS',
  REMOVE_SPACE_FAILURE: 'SPACES/REMOVE_SPACE_FAILURE'
};
